### ISSUE TITLE
Cannot resolve com.epam.reportportal:agent-java-cucumber:5.1.0-RC-2

### ISSUE THREAD

**Issue by restagner** [reportportal/agent-java-cucumber#74]
I work for a large US media company (arguably, #1 in us) and we are using Artifactory as our in-house Maven repository.  Each time I attempt to ingest agent-java-cucumber from my local project, I get the following error

```text
Cannot resolve com.epam.reportportal:agent-java-cucumber:5.1.0-RC-2
```

This is not a network issue as referred to in https://github.com/reportportal/agent-java-cucumber/issues/73.  Our company deals with thousands of artifacts stored within Artifactory.  If it was a network issue, our DevOps team would know about it.

Here is an article from StackOverflow that outlines the problem: https://stackoverflow.com/questions/34615341/jenkins-artifactory-plugin-not-generating-pom-file. In the article, it states

> So indeed you would need the jar and the .pom file

It appears that Maven Central is missing the pom file. The jar file is available, but no pom file.

As you can see, this issue is tied to the source artifact -- i.e. the one currently deployed to Maven Central.  I am requesting that this gets investigated in the hopes that the pom files are deployed alongside each of the `com.epam.reportportal` artifacts

- agent-java-cucumber (v5.1.0-RC-2)
- client-java (v5.1.0-RC-6)
- commons-model (v5.0.0)

**Comment by HardNorth** [comment]
I'm very sorry about your case, but here is the pom file: https://repo1.maven.org/maven2/com/epam/reportportal/agent-java-cucumber/5.1.0-RC-2/agent-java-cucumber-5.1.0-RC-2.pom

As you see it's open and accessible. Actually, if you would know the process of publishing on Maven Central, there is no chance at leat for us to publish invalid artifact. Bugged probably, but not invalid, since they perform complex layered check. And the only chance of getting such invalid artifact is when their process broken.

Anyway, you can use any of 10 artifacts published on MAven Central, but newer version will contain bug fixes and new features: https://search.maven.org/artifact/com.epam.reportportal/agent-java-cucumber
